import {
  Building2,
  FileText,
  Monitor,
  Package,
  PackageCheck,
  PackageMinus,
  PackagePlus,
  Plus,
  RefreshCw,
  Settings,
  ShoppingCart,
  Truck,
  Users,
  Warehouse,
  Ticket,
  AlertTriangle,
  TrendingUp,
  DollarSign,
  Calendar,
  List
} from 'lucide-react';
import { HOME_VIEWERS } from '../utils/homeModuleVisibility';

export const actionModuleGroups = [
  {
    path: '/don-hang-kinh-doanh',
    title: 'Đơn hàng & Kinh doanh',
    description: 'Quản lý đơn hàng, báo giá và doanh thu.',
    icon: Package,
    colorScheme: 'blue',
    homeViewers: [HOME_VIEWERS.KINH_DOANH, HOME_VIEWERS.KHO, HOME_VIEWERS.KE_TOAN],
    items: [
      {
        icon: Package,
        title: 'Danh sách đơn hàng',
        description: 'Theo dõi, quản lý và xử lý các đơn hàng của hệ thống.',
        href: '/don-hang',
        colorScheme: 'blue',
      },
      {
        icon: Monitor,
        title: 'Đề nghị xuất máy',
        description: 'Danh sách phiếu đề nghị xuất máy và quản lý luân chuyển thiết bị.',
        href: '/de-nghi-xuat-may',
        colorScheme: 'amber',
      },
      {
        icon: Users,
        title: 'Danh sách khách hàng',
        description: 'Quản lý dữ liệu người liên hệ và theo dõi tài sản, máy móc phân bổ.',
        href: '/khach-hang',
        colorScheme: 'blue',
      },
      {
        icon: Users,
        title: 'Form đăng kí khách hàng mới',
        description: 'Quản lý khách hàng tiềm năng chưa phát sinh hoạt động.',
        href: '/khach-hang-lead',
        colorScheme: 'amber',
      },
      {
        icon: Users,
        title: 'Báo cáo khách hàng',
        description: 'Phân tích dữ liệu khách hàng theo nhân viên và phân loại.',
        href: '/bao-cao/khach-hang',
        colorScheme: 'blue',
      },
      {
        icon: TrendingUp,
        title: 'Báo cáo NVKD',
        description: 'Thống kê hiệu quả kinh doanh của từng nhân viên.',
        href: '/bao-cao/nhan-vien',
        colorScheme: 'green',
      },
      {
        icon: DollarSign,
        title: 'Báo cáo doanh số',
        description: 'Thống kê doanh thu chi tiết theo từng loại máy móc.',
        href: '/bao-cao/doanh-so-may',
        colorScheme: 'yellow',
      },
      {
        icon: AlertTriangle,
        title: 'Báo cáo KH quá hạn',
        description: 'Danh sách khách hàng đã quá hạn thanh toán hoặc bảo trì.',
        href: '/bao-cao/khach-qua-han',
        colorScheme: 'red',
      },
      {
        icon: Monitor,
        title: 'Báo cáo máy theo khách',
        description: 'Theo dõi tồn kho máy tại từng khách hàng theo tháng/quý/năm.',
        href: '/bao-cao/ton-kho-may-khach',
        colorScheme: 'indigo',
      },
      {
        icon: TrendingUp,
        title: 'Báo cáo doanh số',
        description: 'Phân tích doanh số theo khách hàng, NVKD và loại khách.',
        href: '/bao-cao/doanh-so',
        colorScheme: 'emerald',
      },
    ],
  },
  {
    path: '/quan-ly-thiet-bi',
    title: 'Quản lý thiết bị',
    description: 'Theo dõi và quản lý thiết bị hệ thống.',
    icon: Monitor,
    colorScheme: 'purple',
    homeViewers: [HOME_VIEWERS.KHO, HOME_VIEWERS.ADMIN, HOME_VIEWERS.KE_TOAN],
    items: [
      {
        icon: Monitor,
        title: 'Danh sách máy',
        description: 'Theo dõi trạng thái, vị trí và lịch sử cấp phát máy.',
        href: '/may',
        colorScheme: 'slate',
      },
      {
        icon: Package,
        title: 'Danh sách bình',
        description: 'Quản lý RFID, thể tích và theo dõi vị trí vỏ bình.',
        href: '/binh',
        colorScheme: 'teal',
      },
    ],
  },
  {
    path: '/kho',
    title: 'Kho',
    description: 'Quản lý kho hàng, tồn kho và xuất nhập.',
    icon: Warehouse,
    colorScheme: 'amber',
    homeViewers: [HOME_VIEWERS.KHO, HOME_VIEWERS.ADMIN, HOME_VIEWERS.KE_TOAN],
    items: [
      {
        icon: Warehouse,
        title: 'Danh sách Kho',
        description: 'Quản lý sức chứa, vị trí và thủ kho của từng điểm tập kết.',
        href: '/kho/danh-sach',
        colorScheme: 'amber',
      },
      {
        icon: RefreshCw,
        title: 'Điều chuyển kho',
        description: 'Thực hiện chuyển hàng hóa giữa các kho nội bộ.',
        href: '/kho/dieu-chuyen',
        colorScheme: 'emerald',
      },
      {
        icon: List,
        title: 'Danh sách điều chuyển',
        description: 'Theo dõi phiếu điều chuyển, duyệt phiếu và xem lịch sử điều chuyển.',
        href: '/danh-sach-dieu-chuyen',
        colorScheme: 'blue',
      },
    ],
  },
  {
    path: '/mua-hang-nha-cung-cap',
    title: 'Mua hàng & Nhà cung cấp',
    description: 'Quản lý mua hàng và nhà cung cấp.',
    icon: ShoppingCart,
    colorScheme: 'orange',
    homeViewers: [HOME_VIEWERS.KHO, HOME_VIEWERS.ADMIN, HOME_VIEWERS.KE_TOAN],
    items: [
      {
        icon: Building2,
        title: 'Danh sách nhà cung cấp',
        description: 'Quản lý danh sách các đối tác cung cấp vật tư và vỏ bình.',
        href: '/nha-cung-cap',
        colorScheme: 'teal',
      },
      {
        icon: PackagePlus,
        title: 'Nhập hàng từ NCC',
        description: 'Quản lý phiếu nhập hàng hóa từ nhà cung cấp vào kho công ty.',
        href: '/nhap-hang',
        colorScheme: 'emerald',
      },
      {
        icon: PackageMinus,
        title: 'Xuất trả về NCC',
        description: 'Quản lý phiếu xuất trả vỏ bình hoặc máy móc về cho nhà cung cấp.',
        href: '/xuat-tra-ncc',
        colorScheme: 'pink',
      },
      {
        icon: Package,
        title: 'Thống kê đơn hàng',
        description: 'Báo cáo chi tiết lượng hàng xuất theo tháng và năm.',
        href: '/bao-cao/don-xuat',
        colorScheme: 'purple',
      },
    ],
  },
  {
    path: '/van-chuyen',
    title: 'Vận chuyển',
    description: 'Quản lý vận chuyển và giao nhận hàng.',
    icon: Truck,
    colorScheme: 'cyan',
    homeViewers: [HOME_VIEWERS.VAN_CHUYEN],
    items: [
      {
        icon: Truck,
        title: 'Đơn vị vận chuyển',
        description: 'Quản lý danh sách các nhà xe nội bộ và đơn vị thuê ngoài.',
        href: '/don-vi-van-chuyen',
        colorScheme: 'cyan',
      },
      {
        icon: PackageCheck,
        title: 'Nhiệm vụ giao hàng',
        description: 'Giao đơn, thu hồi vỏ, luân chuyển — xác nhận và upload ảnh Cloudinary.',
        href: '/nhiem-vu-giao-hang',
        colorScheme: 'indigo',
      },
      {
        icon: Truck,
        title: 'Lịch sử giao hàng',
        description: 'Lịch sử giao nhận đơn hàng, có thể lọc theo tài xế/người giao.',
        href: '/lich-su-giao-hang',
        colorScheme: 'indigo',
      },
    ],
  },
  {
    path: '/thu-hoi',
    title: 'Thu hồi',
    description: 'Quản lý thu hồi sản phẩm, thiết bị.',
    icon: RefreshCw,
    colorScheme: 'teal',
    homeViewers: [
      HOME_VIEWERS.KINH_DOANH,
      HOME_VIEWERS.CSKH,
      HOME_VIEWERS.ADMIN,
      HOME_VIEWERS.HE_THONG,
    ],
    items: [
      {
        icon: PackageCheck,
        title: 'Thu hồi vỏ bình',
        description: 'Phiếu thu hồi vỏ, xác nhận tài xế (mã bình + ảnh hiện trường), đồng bộ kho.',
        href: '/thu-hoi-vo',
        colorScheme: 'teal',
      },
      {
        icon: Monitor,
        title: 'Thu hồi máy',
        description: 'Quản lý phiếu thu hồi máy từ khách hàng, quét barcode và xuất PDF.',
        href: '/thu-hoi-may',
        colorScheme: 'indigo',
      },
      {
        icon: PackageMinus,
        title: 'Đơn hàng trả về',
        description: 'Theo dõi các đơn hàng bị khách hàng hoàn trả và cần xử lý thu hồi.',
        href: '/don-hang-tra-ve',
        colorScheme: 'rose',
      },
    ],
  },
  {
    path: '/he-thong',
    title: 'Hệ thống',
    description: 'Cấu hình hệ thống và phân quyền.',
    icon: Settings,
    colorScheme: 'slate',
    items: [
      {
        icon: Users,
        title: 'Quản lý người dùng',
        description: 'Quản lý tài khoản, phân quyền tự động và theo dõi lịch sử truy cập.',
        href: '/nguoi-dung',
        colorScheme: 'blue',
      },
      {
        icon: Settings,
        title: 'Phân quyền chi tiết',
        description: 'Thiết lập quyền truy cập và chức năng cho từng nhóm người dùng.',
        href: '/phan-quyen',
        colorScheme: 'slate',
      },
    ],
  },
  {
    path: '/phieu-sua-chua',
    title: 'Ticket sửa chữa',
    description: 'Quản lý ticket sửa chữa và bảo trì.',
    icon: Ticket,
    colorScheme: 'amber',
    homeViewers: [HOME_VIEWERS.ALL],
    items: [
      {
        icon: Ticket,
        title: 'Ticket sửa chữa',
        description: 'Quản lý ticket sửa chữa và bảo trì.',
        href: '/phieu-sua-chua',
        colorScheme: 'amber',
      },
    ],
  },
];

export const actionModuleSectionsByPath = Object.fromEntries(
  actionModuleGroups.map((group) => [
    group.path,
    [
      {
        section: group.title,
        items: group.items.map((item) => ({
          icon: item.icon,
          title: item.title,
          description: item.description,
          colorScheme: item.colorScheme,
          path: item.href,
        })),
      },
    ],
  ])
);

export const allActionSections = actionModuleGroups.map((group) => ({
  section: group.title,
  items: group.items.map((item) => ({
    icon: item.icon,
    title: item.title,
    description: item.description,
    colorScheme: item.colorScheme,
    path: item.href,
  })),
}));
