import {
  FileText,
  Users,
  Megaphone,
  ShoppingCart,
  Package,
  PackagePlus,
  PackageMinus,
  PackageCheck,
  Monitor,
  Warehouse,
  Truck,
  RefreshCw,
  Settings,
  Layers,
  UserPlus,
  Plus,
  Gift,
  Building2,
} from 'lucide-react';

export const actionModuleGroups = [
  {
    path: '/don-hang-kinh-doanh',
    title: 'Đơn hàng & Kinh doanh',
    description: 'Đơn hàng, khách hàng và khuyến mãi.',
    icon: Package,
    colorScheme: 'blue',
    items: [
      {
        icon: Package,
        title: 'Danh sách đơn hàng',
        description: 'Theo dõi, quản lý và xử lý các đơn hàng của hệ thống.',
        href: '/don-hang',
        colorScheme: 'blue',
      },
      {
        icon: Plus,
        title: 'Thêm đơn hàng',
        description: 'Tạo mới đơn hàng nhanh chóng với các mẫu thông tin có sẵn.',
        href: '/don-hang/tao',
        colorScheme: 'green',
      },
      {
        icon: Users,
        title: 'Danh sách khách hàng',
        description: 'Quản lý dữ liệu người liên hệ và theo dõi tài sản, máy móc phân bổ.',
        href: '/khach-hang',
        colorScheme: 'blue',
      },
      {
        icon: UserPlus,
        title: 'Thêm khách hàng',
        description: 'Tạo hồ sơ khách hàng, đối tác mới vào cơ sở dữ liệu.',
        href: '/khach-hang/tao',
        colorScheme: 'pink',
      },
      {
        icon: Gift,
        title: 'Danh sách Khuyến mãi',
        description: 'Quản lý mã khuyến mãi, khấu trừ bình cho khách hàng và đại lý.',
        href: '/khuyen-mai',
        colorScheme: 'amber',
      },
      {
        icon: Plus,
        title: 'Tạo mã khuyến mãi',
        description: 'Thiết lập chương trình khuyến mãi bình mới cho khách hàng.',
        href: '/khuyen-mai/tao',
        colorScheme: 'orange',
      },
    ],
  },
  {
    path: '/quan-ly-thiet-bi',
    title: 'Quản lý thiết bị',
    description: 'Quản lý máy, bình và trạng thái sử dụng.',
    icon: Monitor,
    colorScheme: 'purple',
    items: [
      {
        icon: Monitor,
        title: 'Danh sách máy',
        description: 'Theo dõi trạng thái, vị trí và lịch sử cấp phát máy.',
        href: '/may',
        colorScheme: 'slate',
      },
      {
        icon: Plus,
        title: 'Thêm máy mới',
        description: 'Khai báo serial, bluetooth và cấu hình máy mới vào kho.',
        href: '/may/tao',
        colorScheme: 'purple',
      },
      {
        icon: Package,
        title: 'Danh sách bình',
        description: 'Quản lý RFID, thể tích và theo dõi vị trí vỏ bình.',
        href: '/binh',
        colorScheme: 'teal',
      },
      {
        icon: Plus,
        title: 'Thêm bình mới',
        description: 'Nhập vỏ bình mới vào hệ thống thông qua mã quét RFID.',
        href: '/binh/tao',
        colorScheme: 'orange',
      },
    ],
  },
  {
    path: '/kho',
    title: 'Kho',
    description: 'Quản lý kho tổng và thêm điểm kho mới.',
    icon: Warehouse,
    colorScheme: 'amber',
    items: [
      {
        icon: Warehouse,
        title: 'Danh sách Kho',
        description: 'Quản lý sức chứa, vị trí và thủ kho của từng điểm tập kết.',
        href: '/kho/danh-sach',
        colorScheme: 'amber',
      },
      {
        icon: Plus,
        title: 'Thêm kho mới',
        description: 'Thêm địa điểm lưu trữ mới vào mạng lưới phân phối.',
        href: '/kho/tao',
        colorScheme: 'red',
      },
    ],
  },
  {
    path: '/mua-hang-nha-cung-cap',
    title: 'Mua hàng & Nhà cung cấp',
    description: 'Nhà cung cấp, nhập hàng và xuất trả.',
    icon: ShoppingCart,
    colorScheme: 'orange',
    items: [
      {
        icon: Building2,
        title: 'Danh sách nhà cung cấp',
        description: 'Quản lý danh sách các đối tác cung cấp vật tư và vỏ bình.',
        href: '/nha-cung-cap',
        colorScheme: 'teal',
      },
      {
        icon: Plus,
        title: 'Thêm nhà cung cấp',
        description: 'Khai báo thông tin đối tác cung cấp mới vào hệ thống.',
        href: '/nha-cung-cap/tao',
        colorScheme: 'cyan',
      },
      {
        icon: PackagePlus,
        title: 'Nhập hàng từ NCC',
        description: 'Quản lý phiếu nhập hàng hóa từ nhà cung cấp vào kho công ty.',
        href: '/nhap-hang',
        colorScheme: 'emerald',
      },
      {
        icon: FileText,
        title: 'Tạo phiếu nhập kho',
        description: 'Lập phiếu nhập mới: chọn NCC, kho nhận, khai báo hàng hóa chi tiết.',
        href: '/phieu-nhap/tao',
        colorScheme: 'green',
      },
      {
        icon: PackageMinus,
        title: 'Xuất trả về NCC',
        description: 'Quản lý phiếu xuất trả vỏ bình hoặc máy móc về cho nhà cung cấp.',
        href: '/xuat-tra-ncc',
        colorScheme: 'pink',
      },
      {
        icon: FileText,
        title: 'Tạo phiếu xuất trả',
        description: 'Lập phiếu xuất mới: chọn kho, NCC nhận và điền hàng hóa cần trả.',
        href: '/phieu-xuat/tao',
        colorScheme: 'orange',
      },
    ],
  },
  {
    path: '/van-chuyen',
    title: 'Vận chuyển',
    description: 'Đơn vị vận chuyển và cấu hình đối tác giao nhận.',
    icon: Truck,
    colorScheme: 'cyan',
    items: [
      {
        icon: Truck,
        title: 'Đơn vị vận chuyển',
        description: 'Quản lý danh sách các nhà xe nội bộ và đơn vị thuê ngoài.',
        href: '/don-vi-van-chuyen',
        colorScheme: 'cyan',
      },
      {
        icon: Truck,
        title: 'Thêm ĐVVC mới',
        description: 'Tạo hồ sơ công ty và người quản lý vận chuyển mới.',
        href: '/don-vi-van-chuyen/tao',
        colorScheme: 'pink',
      },
    ],
  },
  {
    path: '/thu-hoi',
    title: 'Thu hồi',
    description: 'Thu hồi vỏ và tạo phiếu thu hồi tại hiện trường.',
    icon: RefreshCw,
    colorScheme: 'teal',
    items: [
      {
        icon: PackageCheck,
        title: 'Thu hồi vỏ bình',
        description: 'Quản lý phiếu thu hồi vỏ bình từ khách hàng, quét barcode và xuất PDF.',
        href: '/thu-hoi-vo',
        colorScheme: 'teal',
      },
      {
        icon: FileText,
        title: 'Tạo phiếu thu hồi',
        description: 'Lập phiếu thu hồi mới: chọn KH, quét barcode vỏ bình, chụp ảnh hiện trường.',
        href: '/phieu-thu-hoi/tao',
        colorScheme: 'cyan',
      },
    ],
  },
  {
    path: '/vat-tu',
    title: 'Vật tư',
    description: 'Quản lý danh mục vật tư và khai báo vật tư mới.',
    icon: Layers,
    colorScheme: 'cyan',
    items: [
      {
        icon: Layers,
        title: 'Danh sách nguồn vật tư',
        description: 'Lưu trữ danh mục cấu kiện cơ bản phục vụ lắp ráp hệ thống.',
        href: '/vat-tu/danh-sach',
        colorScheme: 'cyan',
      },
      {
        icon: FileText,
        title: 'Thêm mới vật tư',
        description: 'Khai báo thông số cấu kiện mới vào từ điển chung.',
        href: '/vat-tu/tao',
        colorScheme: 'emerald',
      },
    ],
  },
  {
    path: '/he-thong',
    title: 'Hệ thống',
    description: 'Người dùng, vai trò và phân quyền hệ thống.',
    icon: Settings,
    colorScheme: 'slate',
    items: [
      {
        icon: Users,
        title: 'Quản lý người dùng',
        description: 'Quản lý tài khoản, phân quyền tự động và theo dõi lịch sử truy cập.',
        href: '/nguoi-dung',
        colorScheme: 'blue',
      },
      {
        icon: UserPlus,
        title: 'Thêm người dùng',
        description: 'Cấp tài khoản mới cho nhân viên hoặc người quản lý trên hệ thống.',
        href: '/nguoi-dung/tao',
        colorScheme: 'pink',
      },
      {
        icon: Settings,
        title: 'Phân quyền chi tiết',
        description: 'Thiết lập quyền truy cập và chức năng cho từng nhóm người dùng.',
        href: '/phan-quyen',
        colorScheme: 'slate',
      },
    ],
  },
];

export const actionModuleSectionsByPath = Object.fromEntries(
  actionModuleGroups.map((group) => [
    group.path,
    [
      {
        section: group.title,
        items: group.items.map((item) => ({
          icon: item.icon,
          title: item.title,
          description: item.description,
          colorScheme: item.colorScheme,
          path: item.href,
        })),
      },
    ],
  ])
);

export const allActionSections = actionModuleGroups.map((group) => ({
  section: group.title,
  items: group.items.map((item) => ({
    icon: item.icon,
    title: item.title,
    description: item.description,
    colorScheme: item.colorScheme,
    path: item.href,
  })),
}));
