import {
  Building2,
  FileText,
  Gift,
  Layers,
  Monitor,
  Package,
  PackageCheck,
  PackageMinus,
  PackagePlus,
  Plus,
  RefreshCw,
  Settings,
  ShoppingCart,
  Truck,
  UserPlus,
  Users,
  Warehouse,
  Ticket,
  AlertTriangle,
  TrendingUp,
  DollarSign,
  Calendar
} from 'lucide-react';

export const actionModuleGroups = [
  {
    path: '/don-hang-kinh-doanh',
    title: 'Đơn hàng & Kinh doanh',
    description: 'Đơn hàng, khách hàng và khuyến mãi.',
    icon: Package,
    colorScheme: 'blue',
    items: [
      {
        icon: Package,
        title: 'Danh sách đơn hàng',
        description: 'Theo dõi, quản lý và xử lý các đơn hàng của hệ thống.',
        href: '/don-hang',
        colorScheme: 'blue',
      },
      {
        icon: Monitor,
        title: 'Đề nghị xuất máy',
        description: 'Danh sách phiếu đề nghị xuất máy và quản lý luân chuyển thiết bị.',
        href: '/de-nghi-xuat-may',
        colorScheme: 'amber',
      },
      {
        icon: Truck,
        title: 'Lịch sử giao hàng',
        description: 'Lịch sử giao nhận đơn hàng, có thể lọc theo tài xế/người giao.',
        href: '/lich-su-giao-hang',
        colorScheme: 'indigo',
      },
      {
        icon: Users,
        title: 'Danh sách khách hàng',
        description: 'Quản lý dữ liệu người liên hệ và theo dõi tài sản, máy móc phân bổ.',
        href: '/khach-hang',
        colorScheme: 'blue',
      },
      {
        icon: Users,
        title: 'Form đăng kí khách hàng mới',
        description: 'Quản lý khách hàng tiềm năng chưa phát sinh hoạt động.',
        href: '/khach-hang-lead',
        colorScheme: 'amber',
      },
      {
        icon: Gift,
        title: 'Danh sách Khuyến mãi',
        description: 'Quản lý mã khuyến mãi, khấu trừ bình cho khách hàng và đại lý.',
        href: '/khuyen-mai',
        colorScheme: 'amber',
      },
      {
        icon: Users,
        title: 'Báo cáo khách hàng',
        description: 'Phân tích dữ liệu khách hàng theo nhân viên và phân loại.',
        href: '/bao-cao/khach-hang',
        colorScheme: 'blue',
      },
      {
        icon: TrendingUp,
        title: 'Báo cáo NVKD',
        description: 'Thống kê hiệu quả kinh doanh của từng nhân viên.',
        href: '/bao-cao/nhan-vien',
        colorScheme: 'green',
      },
      {
        icon: DollarSign,
        title: 'Báo cáo doanh số',
        description: 'Thống kê doanh thu chi tiết theo từng loại máy móc.',
        href: '/bao-cao/doanh-so-may',
        colorScheme: 'yellow',
      },
      {
        icon: AlertTriangle,
        title: 'Báo cáo KH quá hạn',
        description: 'Danh sách khách hàng đã quá hạn thanh toán hoặc bảo trì.',
        href: '/bao-cao/khach-qua-han',
        colorScheme: 'red',
      },
      {
        icon: PackageCheck,
        title: 'Báo cáo bình theo khách',
        description: 'Theo dõi tồn kho bình tại từng khách hàng theo tháng/quý/năm.',
        href: '/bao-cao/binh-theo-khach',
        colorScheme: 'indigo',
      },
      {
        icon: Monitor,
        title: 'Báo cáo máy theo khách',
        description: 'Theo dõi tồn kho máy tại từng khách hàng theo tháng/quý/năm.',
        href: '/bao-cao/ton-kho-may-khach',
        colorScheme: 'indigo',
      },
      {
        icon: TrendingUp,
        title: 'Báo cáo doanh số',
        description: 'Phân tích doanh số theo khách hàng, NVKD và loại khách.',
        href: '/bao-cao/doanh-so',
        colorScheme: 'emerald',
      },
    ],
  },
  {
    path: '/quan-ly-thiet-bi',
    title: 'Quản lý thiết bị',
    description: 'Quản lý máy, bình và trạng thái sử dụng.',
    icon: Monitor,
    colorScheme: 'purple',
    items: [
      {
        icon: Monitor,
        title: 'Danh sách máy',
        description: 'Theo dõi trạng thái, vị trí và lịch sử cấp phát máy.',
        href: '/may',
        colorScheme: 'slate',
      },
      {
        icon: Package,
        title: 'Danh sách bình',
        description: 'Quản lý RFID, thể tích và theo dõi vị trí vỏ bình.',
        href: '/binh',
        colorScheme: 'teal',
      },
      {
        icon: Monitor,
        title: 'Thống kê máy',
        description: 'Báo cáo trạng thái và hiệu quả sử dụng máy móc.',
        href: '/bao-cao/may-banh',
        colorScheme: 'slate',
      },
      {
        icon: AlertTriangle,
        title: 'Báo cáo bình lỗi',
        description: 'Thống kê các vỏ bình bị hỏng hoặc cần bảo trì.',
        href: '/bao-cao/binh-loi',
        colorScheme: 'red',
      },
      {
        icon: AlertTriangle,
        title: 'Báo cáo bình quá hạn',
        description: 'Theo dõi các vỏ bình đã quá hạn thu hồi tại khách hàng.',
        href: '/bao-cao/binh-qua-han',
        colorScheme: 'orange',
      },
      {
        icon: Calendar,
        title: 'Báo cáo quý',
        description: 'Tổng hợp báo cáo bảo trì và vận hành theo từng quý.',
        href: '/bao-cao/ton-kho-binh-khach',
        colorScheme: 'amber',
      },
      {
        icon: AlertTriangle,
        title: 'Báo cáo lỗi thiết bị',
        description: 'Phân tích tỷ lệ hỏng hóc máy/bình theo thời gian.',
        href: '/bao-cao/loi-thiet-bi',
        colorScheme: 'rose',
      },
    ],
  },
  {
    path: '/kho',
    title: 'Kho',
    description: 'Quản lý kho tổng và thêm điểm kho mới.',
    icon: Warehouse,
    colorScheme: 'amber',
    items: [
      {
        icon: Warehouse,
        title: 'Danh sách Kho',
        description: 'Quản lý sức chứa, vị trí và thủ kho của từng điểm tập kết.',
        href: '/kho/danh-sach',
        colorScheme: 'amber',
      },
      {
        icon: FileText,
        title: 'Báo cáo kho',
        description: 'Xem chi tiết số lượng tồn kho từng loại máy, bình, vật tư.',
        href: '/bao-cao/kho',
        colorScheme: 'blue',
      },
      {
        icon: RefreshCw,
        title: 'Điều chuyển kho',
        description: 'Thực hiện chuyển hàng hóa giữa các kho nội bộ.',
        href: '/kho/dieu-chuyen',
        colorScheme: 'emerald',
      },
    ],
  },
  {
    path: '/mua-hang-nha-cung-cap',
    title: 'Mua hàng & Nhà cung cấp',
    description: 'Nhà cung cấp, nhập hàng và xuất trả.',
    icon: ShoppingCart,
    colorScheme: 'orange',
    items: [
      {
        icon: Building2,
        title: 'Danh sách nhà cung cấp',
        description: 'Quản lý danh sách các đối tác cung cấp vật tư và vỏ bình.',
        href: '/nha-cung-cap',
        colorScheme: 'teal',
      },
      {
        icon: PackagePlus,
        title: 'Nhập hàng từ NCC',
        description: 'Quản lý phiếu nhập hàng hóa từ nhà cung cấp vào kho công ty.',
        href: '/nhap-hang',
        colorScheme: 'emerald',
      },
      {
        icon: PackageMinus,
        title: 'Xuất trả về NCC',
        description: 'Quản lý phiếu xuất trả vỏ bình hoặc máy móc về cho nhà cung cấp.',
        href: '/xuat-tra-ncc',
        colorScheme: 'pink',
      },
      {
        icon: Package,
        title: 'Thống kê đơn hàng',
        description: 'Báo cáo chi tiết lượng hàng xuất theo tháng và năm.',
        href: '/bao-cao/don-xuat',
        colorScheme: 'purple',
      },
    ],
  },
  {
    path: '/van-chuyen',
    title: 'Vận chuyển',
    description: 'Đơn vị vận chuyển và cấu hình đối tác giao nhận.',
    icon: Truck,
    colorScheme: 'cyan',
    items: [
      {
        icon: Truck,
        title: 'Đơn vị vận chuyển',
        description: 'Quản lý danh sách các nhà xe nội bộ và đơn vị thuê ngoài.',
        href: '/don-vi-van-chuyen',
        colorScheme: 'cyan',
      },
      {
        icon: PackageCheck,
        title: 'Nhiệm vụ giao hàng',
        description: 'Danh sách các đơn hàng cần giao, xác nhận thành công và tải ảnh bằng chứng.',
        href: '/nhiem-vu-giao-hang',
        colorScheme: 'indigo',
      },
    ],
  },
  {
    path: '/thu-hoi',
    title: 'Thu hồi',
    description: 'Thu hồi vỏ và tạo phiếu thu hồi tại hiện trường.',
    icon: RefreshCw,
    colorScheme: 'teal',
    items: [
      {
        icon: PackageCheck,
        title: 'Thu hồi vỏ bình',
        description: 'Quản lý phiếu thu hồi vỏ bình từ khách hàng, quét barcode và xuất PDF.',
        href: '/thu-hoi-vo',
        colorScheme: 'teal',
      },
      {
        icon: Monitor,
        title: 'Thu hồi máy',
        description: 'Quản lý phiếu thu hồi máy từ khách hàng, quét barcode và xuất PDF.',
        href: '/thu-hoi-may',
        colorScheme: 'indigo',
      },
      {
        icon: PackageMinus,
        title: 'Đơn hàng trả về',
        description: 'Theo dõi các đơn hàng bị khách hàng hoàn trả và cần xử lý thu hồi.',
        href: '/don-hang-tra-ve',
        colorScheme: 'rose',
      },
    ],
  },
  {
    path: '/vat-tu',
    title: 'Vật tư',
    description: 'Quản lý danh mục vật tư và khai báo vật tư mới.',
    icon: Layers,
    colorScheme: 'cyan',
    items: [
      {
        icon: Layers,
        title: 'Danh sách nguồn vật tư',
        description: 'Lưu trữ danh mục cấu kiện cơ bản phục vụ lắp ráp hệ thống.',
        href: '/vat-tu/danh-sach',
        colorScheme: 'cyan',
      },
    ],
  },
  {
    path: '/he-thong',
    title: 'Hệ thống',
    description: 'Người dùng, vai trò và phân quyền hệ thống.',
    icon: Settings,
    colorScheme: 'slate',
    items: [
      {
        icon: Users,
        title: 'Quản lý người dùng',
        description: 'Quản lý tài khoản, phân quyền tự động và theo dõi lịch sử truy cập.',
        href: '/nguoi-dung',
        colorScheme: 'blue',
      },
      {
        icon: UserPlus,
        title: 'Thêm người dùng',
        description: 'Cấp tài khoản mới cho nhân viên hoặc người quản lý trên hệ thống.',
        href: '/nguoi-dung/tao',
        colorScheme: 'pink',
      },
      {
        icon: Settings,
        title: 'Phân quyền chi tiết',
        description: 'Thiết lập quyền truy cập và chức năng cho từng nhóm người dùng.',
        href: '/phan-quyen',
        colorScheme: 'slate',
      },
    ],
  },
  {
    path: '/phieu-sua-chua',
    title: 'Ticket sửa chữa',
    description: 'Quản lý phiếu yêu cầu và tiến độ sửa chữa thiết bị.',
    icon: Ticket,
    colorScheme: 'amber',
    items: [
      {
        icon: Ticket,
        title: 'Ticket sửa chữa',
        description: 'Quản lý phiếu yêu cầu và tiến độ sửa chữa thiết bị.',
        href: '/phieu-sua-chua',
        colorScheme: 'amber',
      },
    ],
  },
];

export const actionModuleSectionsByPath = Object.fromEntries(
  actionModuleGroups.map((group) => [
    group.path,
    [
      {
        section: group.title,
        items: group.items.map((item) => ({
          icon: item.icon,
          title: item.title,
          description: item.description,
          colorScheme: item.colorScheme,
          path: item.href,
        })),
      },
    ],
  ])
);

export const allActionSections = actionModuleGroups.map((group) => ({
  section: group.title,
  items: group.items.map((item) => ({
    icon: item.icon,
    title: item.title,
    description: item.description,
    colorScheme: item.colorScheme,
    path: item.href,
  })),
}));
