import {
  Layout,
  Package,
  Monitor,
  Warehouse,
  ShoppingCart,
  Truck,
  RefreshCw,
  Layers,
  Settings2,
  Building2,
  PackagePlus,
  PackageMinus,
  PackageCheck,
  Gift,
  ShieldCheck,
} from 'lucide-react';

export const sidebarMenu = [
  { path: '/trang-chu', label: 'Bảng điều khiển', icon: Layout },
  { path: '/don-hang-kinh-doanh', label: 'Đơn hàng & Kinh doanh', icon: Package },
  { path: '/quan-ly-thiet-bi', label: 'Quản lý thiết bị', icon: Monitor },
  { path: '/kho', label: 'Kho', icon: Warehouse },
  { path: '/mua-hang-nha-cung-cap', label: 'Mua hàng & Nhà cung cấp', icon: ShoppingCart },
  { path: '/van-chuyen', label: 'Vận chuyển', icon: Truck },
  { path: '/thu-hoi', label: 'Thu hồi', icon: RefreshCw },
  { path: '/vat-tu', label: 'Vật tư', icon: Layers },
  { path: '/he-thong', label: 'Hệ thống', icon: Settings2 },
];

export const extraMenuItems = [
  { path: '/don-hang', label: 'Danh sách đơn hàng', icon: Package },
  { path: '/khach-hang', label: 'Danh sách khách hàng', icon: Building2 },
  { path: '/khach-hang/tao', label: 'Thêm khách hàng', icon: Building2 },
  { path: '/may', label: 'Danh sách máy', icon: Monitor },
  { path: '/may/tao', label: 'Thêm máy mới', icon: Monitor },
  { path: '/binh', label: 'Danh sách bình', icon: Package },
  { path: '/binh/tao', label: 'Thêm bình mới', icon: Package },
  { path: '/kho/danh-sach', label: 'Danh sách kho', icon: Warehouse },
  { path: '/kho/tao', label: 'Thêm kho mới', icon: Warehouse },
  { path: '/nha-cung-cap', label: 'Danh sách nhà cung cấp', icon: Building2 },
  { path: '/nha-cung-cap/tao', label: 'Thêm nhà cung cấp', icon: Building2 },
  { path: '/nhap-hang', label: 'Nhập hàng từ NCC', icon: PackagePlus },
  { path: '/xuat-tra-ncc', label: 'Xuất trả về NCC', icon: PackageMinus },
  { path: '/phieu-nhap/tao', label: 'Tạo phiếu nhập kho', icon: PackagePlus },
  { path: '/phieu-xuat/tao', label: 'Tạo phiếu xuất trả', icon: PackageMinus },
  { path: '/thu-hoi-vo', label: 'Thu hồi vỏ bình', icon: PackageCheck },
  { path: '/phieu-thu-hoi/tao', label: 'Tạo phiếu thu hồi', icon: PackageCheck },
  { path: '/don-vi-van-chuyen', label: 'Đơn vị vận chuyển', icon: Truck },
  { path: '/don-vi-van-chuyen/tao', label: 'Thêm ĐVVC mới', icon: Truck },
  { path: '/vat-tu/danh-sach', label: 'Nguồn vật tư', icon: Layers },
  { path: '/vat-tu/tao', label: 'Thêm mới vật tư', icon: Layers },
  { path: '/khuyen-mai', label: 'Khuyến mãi', icon: Gift },
  { path: '/khuyen-mai/tao', label: 'Tạo mã khuyến mãi', icon: Gift },
  { path: '/nguoi-dung', label: 'Người dùng', icon: Building2 },
  { path: '/nguoi-dung/tao', label: 'Thêm người dùng', icon: Building2 },
  { path: '/phan-quyen', label: 'Phân quyền', icon: ShieldCheck },
  { path: '/phan-quyen/tao', label: 'Tạo phân quyền', icon: ShieldCheck },
];
