import {
  Layout,
  Package,
  Monitor,
  Warehouse,
  ShoppingCart,
  Truck,
  RefreshCw,
  Layers,
  Settings2,
  Building2,
  PackagePlus,
  PackageMinus,
  PackageCheck,
  Gift,
  ShieldCheck,
  BarChart3,
} from 'lucide-react';

export const sidebarMenu = [
  { path: '/trang-chu', label: 'Bảng điều khiển', icon: Layout, color: 'text-blue-500' },
  { path: '/thong-ke', label: 'Thống kê', icon: BarChart3, color: 'text-amber-500' },
  { path: '/don-hang-kinh-doanh', label: 'Đơn hàng & Kinh doanh', icon: Package, color: 'text-emerald-500' },
  { path: '/quan-ly-thiet-bi', label: 'Quản lý thiết bị', icon: Monitor, color: 'text-cyan-500' },
  { path: '/kho', label: 'Kho', icon: Warehouse, color: 'text-orange-500' },
  { path: '/mua-hang-nha-cung-cap', label: 'Mua hàng & Nhà cung cấp', icon: ShoppingCart, color: 'text-rose-500' },
  { path: '/van-chuyen', label: 'Vận chuyển', icon: Truck, color: 'text-sky-500' },
  { path: '/thu-hoi', label: 'Thu hồi', icon: RefreshCw, color: 'text-teal-500' },
  { path: '/vat-tu', label: 'Vật tư', icon: Layers, color: 'text-slate-500' },
  { path: '/he-thong', label: 'Hệ thống', icon: Settings2, color: 'text-indigo-500' },
];

export const extraMenuItems = [
  { path: '/trang-chu', label: 'Bảng điều khiển', icon: Layout },
  { path: '/thong-ke', label: 'Thống kê tổng quan', icon: BarChart3 },
  { path: '/bao-cao/khach-hang', label: 'Báo cáo khách hàng', icon: BarChart3 },
  { path: '/bao-cao/nhan-vien', label: 'Báo cáo NVKD', icon: BarChart3 },
  { path: '/bao-cao/binh-qua-han', label: 'Báo cáo bình quá hạn', icon: BarChart3 },
  { path: '/bao-cao/khach-qua-han', label: 'Báo cáo KH quá hạn', icon: BarChart3 },
  { path: '/bao-cao/binh-loi', label: 'Báo cáo bình lỗi', icon: BarChart3 },
  { path: '/bao-cao/may-banh', label: 'Báo cáo máy', icon: BarChart3 },
  { path: '/bao-cao/don-xuat', label: 'Báo cáo đơn xuất', icon: BarChart3 },
  { path: '/bao-cao/doanh-so-may', label: 'Báo cáo doanh số', icon: BarChart3 },
  { path: '/bao-cao/bao-cao-quy', label: 'Báo cáo quý', icon: BarChart3 },
  { path: '/bao-cao/binh-theo-khach', label: 'Báo cáo bình theo khách', icon: BarChart3 },
  { path: '/bao-cao/ton-kho-binh-khach', label: 'Báo cáo bình theo khách', icon: BarChart3 },
  { path: '/bao-cao/ton-kho-may-khach', label: 'Báo cáo máy theo khách', icon: BarChart3 },
  { path: '/bao-cao/doanh-so', label: 'Báo cáo doanh số', icon: BarChart3 },
  { path: '/bao-cao/loi-thiet-bi', label: 'Báo cáo lỗi thiết bị', icon: BarChart3 },
  { path: '/bao-cao/doanh-so-san-luong', label: 'Doanh số/Sản lượng', icon: BarChart3 },
  { path: '/don-hang', label: 'Danh sách đơn hàng', icon: Package },
  { path: '/khach-hang', label: 'Danh sách khách hàng', icon: Building2 },
  { path: '/khach-hang/tao', label: 'Thêm khách hàng', icon: Building2 },
  { path: '/may', label: 'Danh sách máy', icon: Monitor },
  { path: '/binh', label: 'Danh sách bình', icon: Package },
  { path: '/binh/tao', label: 'Thêm bình mới', icon: Package },
  { path: '/kho/danh-sach', label: 'Danh sách kho', icon: Warehouse },
  { path: '/kho/tao', label: 'Thêm kho mới', icon: Warehouse },
  { path: '/nha-cung-cap', label: 'Danh sách nhà cung cấp', icon: Building2 },
  { path: '/nha-cung-cap/tao', label: 'Thêm nhà cung cấp', icon: Building2 },
  { path: '/nhap-hang', label: 'Nhập hàng từ NCC', icon: PackagePlus },
  { path: '/xuat-tra-ncc', label: 'Xuất trả về NCC', icon: PackageMinus },
  { path: '/phieu-nhap/tao', label: 'Tạo phiếu nhập kho', icon: PackagePlus },
  { path: '/phieu-xuat/tao', label: 'Tạo phiếu xuất trả', icon: PackageMinus },
  { path: '/thu-hoi-vo', label: 'Thu hồi vỏ bình', icon: PackageCheck },
  { path: '/thu-hoi-may', label: 'Thu hồi máy', icon: Monitor },
  { path: '/don-vi-van-chuyen', label: 'Đơn vị vận chuyển', icon: Truck },
  { path: '/don-vi-van-chuyen/tao', label: 'Thêm ĐVVC mới', icon: Truck },
  { path: '/vat-tu/danh-sach', label: 'Nguồn vật tư', icon: Layers },
  { path: '/vat-tu/tao', label: 'Thêm mới vật tư', icon: Layers },
  { path: '/khuyen-mai', label: 'Khuyến mãi', icon: Gift },
  { path: '/khuyen-mai/tao', label: 'Tạo mã khuyến mãi', icon: Gift },
  { path: '/nguoi-dung', label: 'Người dùng', icon: Building2 },
  { path: '/nguoi-dung/tao', label: 'Thêm người dùng', icon: Building2 },
  { path: '/phan-quyen', label: 'Phân quyền', icon: ShieldCheck },
  { path: '/phan-quyen/tao', label: 'Tạo phân quyền', icon: ShieldCheck },
];
